getsafle/safle-keyless-transactions

README.md
Readme file updated with functional specs and other improvements.
=> updated readme with WIP

.gitignore, .vscode/launch.json, README.md, index.js, package-lock.json, package.json, utils/helper.js
- users can now initialize the constructor by passing the authentication token.
- added a function to generate the access token for the API calls which is used to set or get the encrypted private key.
The access token is sent to the server through the headers in the request.
- Once the encrypted private key is decrypted, it calls a utility function to sign and sent the transaction to the blockchain.
=> added a constructor for setting auth token and implemented some utility functions to generate access token,sign and send transaction.

.gitignore, .vscode/launch.json, index.js, package-lock.json, package.json
Added methods for generating a new wallet and also to import a wallet using the 12-word seed phrase.
=> added wallet generation methods.

index.js
- Implemented a function to generate 2 random numbers and also verify the seed phrases based on those 2 numbers.
- Moved the wallet related methods inside the class.
- Updated the response structure for wallet generation and wallet import.
All the wallet related data will be inside wallet object.
=> Implemented methods to generate 2 random numbers and also validate seed phrases. 

README.md, src/index.js
Implemented separate class for wallet related methods.
=> Wallet class

README.md, package-lock.json, package.json, src/config/index.js, src/index.js, src/utils/helper.js
- The method to get the encrypted private key is moved to utils and it gets invoked inside **signKey** method.
- The method to sign the transactions **signKey** calls the **getKey** method to get the encrypted private key after validating the password.
- The encrypted private key is decrypted and the transaction is signed and sent to the blockchain.
- Updated method names.
- Token gets stored in the local storage when login function is called.
- Logout function is also implemented
=> Moved getKey method to utils and it gets invoked inside signKeymethod.

README.md, package.json, src/index.js
- Updated readme file.
- Destructured the encryptKey return value.
=> Updated readme file and destructured the encryptKey return value.

README.md, package.json, src/index.js, src/utils/helper.js
Encrypted private key should be passed inside the **changePassword** method.
Hence, the method **getEncryptedPrivateKey** should be called and the encrypted private key should be passed inside the change password method.
=> Encrypted private key should be retrieved before calling the change password method.

README.md, package.json, src/constants/response/index.js, src/index.js, src/utils/helper.js
Added a method to delete a user's encrypted private key from Inblox KMS.
=> Method to delete encrypted private key from Inblox KMS.

README.md, package.json, src/config/index.js, src/constants/response/index.js, src/index.js, src/utils/helper.js
Created a master method for Handlename registration which calls the **storeKey** method and then relays the signed transaction to the relayer.
=> Master method for handlename registration

src/index.js, src/utils/helper.js
Add specific tokens to the request headers of **store**, **get** and **delete** encrypted private key methods.
=> Add specific tokens to the request headers of store, get and delete encrypted private key methods.

package.json, src/config/index.js, src/utils/helper.js
Removed the network check before initializing web3 during data signing.
=> Removed network check before web3 initialization

README.md, package.json
Updated all the instances of inblox to safle in the README file.
=> Updated README file

.gitignore, package-lock.json, package.json, src/index.js, src/utils/helper.js
created a method to generate encryptedEncryptionKey.
=> Method to generate encryptedEncryptionKey

.gitignore, package-lock.json, package.json, src/index.js, src/utils/helper.js
Created a method to generate hashedPassword.
=> Feature hashed password generation

.gitignore, package-lock.json, package.json, src/index.js, src/utils/helper.js
Created a method to generate a PDKeyHash using the user's safleId and password.
=> Feature generate PDKeyHash

.gitignore, package-lock.json, package.json, src/index.js, src/utils/helper.js
`signAndSendTx()` function now also accepts `encryptedPrivateKey`.
There will be a checking to ensure `encryptedPrivateKey` value is passed in the parameter. Else it will fetch the value from the cloud.
=> Feature enable pkey input sign tx

src/index.js, src/lib/vault.js
Created a method to generate the vault by passing the user's safleId password for encryption.
=> Feature generate vault

.gitignore, package-lock.json, package.json, src/index.js, src/lib/vault.js, src/utils/helper.js
Created a method to retrieve the vault from the persisted location.
=> Feature retrieve vault

.gitignore, package-lock.json, package.json, src/index.js, src/lib/vault.js, src/utils/helper.js
Created a method to add a new account in the existing keyring.
=> Feature add account

.gitignore, package-lock.json, package.json, src/index.js, src/lib/vault.js, src/utils/helper.js
Created methods to persist the vault.
Additional methods like `generateVaultAndPersist()` and `addAccountAndPersist()` are also created.
=> Feature persist vault

.gitignore, package-lock.json, package.json, src/index.js, src/lib/vault.js, src/utils/helper.js
Created a method to delete the vault from the cloud.
=> Feature delete vault

.gitignore, package-lock.json, package.json, src/index.js, src/lib/vault.js, src/utils/helper.js
Created a method to get the list of accounts.
=> Feature get accounts

.gitignore, package-lock.json, package.json, src/index.js, src/lib/vault.js, src/utils/helper.js
Created a method to export the private key of the address specified.
=> Feature export private key

.gitignore, package-lock.json, package.json, src/index.js, src/lib/vault.js, src/utils/helper.js
Created a method to export the 12-word seed phrase of the keyring.
=> Feature export seeds

.gitignore, package-lock.json, package.json, src/index.js, src/lib/vault.js, src/utils/helper.js
Created a method to sign a message from a particular account present in the keyring.
=> Feature sign message

.gitignore, package-lock.json, package.json, src/index.js, src/lib/vault.js, src/utils/helper.js
Created a method to sign transactions.
=> Feature sign transaction

.gitignore, README.md, package-lock.json, package.json, src/index.js, src/lib/vault.js, src/utils/helper.js
All the methods for vault generation, persistence, update and other vault related operations like signing messages and transactions, export private keys, etc.
=> Feature vault integration

package.json, src/index.js
Moved the password hashing and encryption methods to outside the class.
=> Moved the password hashing and encryption methods to outside the class.
